package com.entity;
// Generated Aug 15, 2018 2:16:27 AM by Hibernate Tools 5.1.8.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name="bill"
    ,catalog="webshop2"
)
@Proxy(lazy = false)
public class Bill  implements java.io.Serializable {


     private String billId;
     private User user;
     private String payment;
     private Date date;
     private  double total;
     private Set<Billdetail> billdetails = new HashSet<Billdetail>(0);

    public Bill() {
    }

	
    public Bill(String billId, User user, String payment) {
        this.billId = billId;
        this.user = user;
        this.payment = payment;
    }
    public Bill(String billId, User user, String payment, Date date, double total, Set<Billdetail> billdetails) {
       this.billId = billId;
       this.user = user;
       this.payment = payment;
       this.date = date;
       this.total = total;
       this.billdetails = billdetails;
    }
   
     @Id 

    
    @Column(name="bill_id", unique=true, nullable=false, length=45)
    public String getBillId() {
        return this.billId;
    }
    
    public void setBillId(String billId) {
        this.billId = billId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="payment", nullable=false, length=45)
    public String getPayment() {
        return this.payment;
    }
    
    public void setPayment(String payment) {
        this.payment = payment;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="total", length=45)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bill")
    public Set<Billdetail> getBilldetails() {
        return this.billdetails;
    }
    
    public void setBilldetails(Set<Billdetail> billdetails) {
        this.billdetails = billdetails;
    }




}


