package com.entity;
// Generated Aug 15, 2018 2:16:27 AM by Hibernate Tools 5.1.8.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="webshop2"
)
@Proxy(lazy = false)
public class Category  implements java.io.Serializable {


     private String categoryId;
     private String categoryName;
     private Set<Product> products = new HashSet<Product>(0);

    public Category() {
    }

	
    public Category(String categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public Category(String categoryId, String categoryName, Set<Product> products) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="category_id", unique=true, nullable=false, length=45)
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="category_name", nullable=false, length=45)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


