package com.entity;
// Generated Aug 15, 2018 2:16:27 AM by Hibernate Tools 5.1.8.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Role generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="role"
    ,catalog="webshop2"
)
@Proxy(lazy = false)
public class Role  implements java.io.Serializable {


     private String roleId;
     private String roleName;
     private Set<Admin> admins = new HashSet<Admin>(0);
     private Set<User> users = new HashSet<User>(0);

    public Role() {
    }

	
    public Role(String roleId, String roleName) {
        this.roleId = roleId;
        this.roleName = roleName;
    }
    public Role(String roleId, String roleName, Set<Admin> admins, Set<User> users) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.admins = admins;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="role_id", unique=true, nullable=false, length=45)
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="role_name", nullable=false, length=45)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set<Admin> getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set<Admin> admins) {
        this.admins = admins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


